import type { BCIRecord } from '@/types/bci';

export const MOCK_BCI_RECORDS: BCIRecord[] = [
  {
    id: 'bci-001',
    title: 'High-Density EEG Motor Cortex Dataset',
    type: 'EEG',
    description:
      '256-channel EEG recording during motor imagery tasks. Ideal for BCI control research and neural decoding studies.',
    longDescription:
      'This dataset contains high-density EEG recordings from 256 active electrodes positioned according to the 10-5 system. Participants performed motor imagery tasks (left hand, right hand, both feet, tongue) across 120 trials per class. The data was acquired at 2048 Hz with a hardware bandpass filter of 0.1–1000 Hz. Artifact rejection was applied using ICA. This dataset is suitable for BCI competition benchmarks, neural decoding, and motor rehabilitation research.',
    dataPoints: 12_800_000,
    duration: '48 hours',
    samplingRate: '2048 Hz',
    channels: 256,
    price: '0.05',
    priceUSD: '$175',
    owner: '0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
    ownerName: 'Dr. Sarah Chen',
    requirements: {
      minEthBalance: '0.1',
      institutionRequired: true,
      purposeRequired: 'Medical Research',
      walletVerification: true,
    },
    tags: ['Motor Cortex', 'Motor Imagery', 'Neural Decoding', 'Rehabilitation'],
    ipfsHash: 'QmXf3rW9mLkP8vTqN2zY7hB4cD6eA1jG5sK0uI9oQ3mR',
    uploadedAt: '2026-01-15',
    verified: true,
    downloads: 34,
    status: 'available',
    maxPurchases: 5,
    purchaseCount: 0,
  },
  {
    id: 'bci-002',
    title: 'Resting-State fMRI Connectivity Atlas',
    type: 'fMRI',
    description:
      'Whole-brain resting-state fMRI data with default mode network parcellation. 3T scanner, 2mm isotropic resolution.',
    longDescription:
      'A comprehensive resting-state fMRI dataset acquired on a Siemens Magnetom Prisma 3T scanner. TR = 1000ms, TE = 30ms, 2mm isotropic voxels, 72 slices with multiband acceleration factor 8. Participants rested with eyes open fixating on a crosshair for 10 minutes. Preprocessing includes motion correction, slice timing, smoothing (6mm FWHM), and nuisance regression. Functional connectivity matrices for 400 ROIs (Schaefer atlas) are included.',
    dataPoints: 36_000,
    duration: '10 min / subject × 80 subjects',
    samplingRate: '1 Hz (TR=1000ms)',
    channels: 72,
    price: '0.12',
    priceUSD: '$420',
    owner: '0x2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c',
    ownerName: 'Prof. Marcus Reid',
    requirements: {
      minEthBalance: '0.2',
      institutionRequired: true,
      purposeRequired: 'Neuroscience Research',
      walletVerification: true,
    },
    tags: ['Default Mode Network', 'Connectivity', 'Resting State', '3T'],
    ipfsHash: 'QmYg4sX0nMlQ9wUqO3aZ8iC5dE7fB2kH6tL1vJ0pN4nS',
    uploadedAt: '2026-01-28',
    verified: true,
    downloads: 19,
    status: 'available',
    maxPurchases: 10,
    purchaseCount: 0,
  },
  {
    id: 'bci-003',
    title: 'ECoG Speech Synthesis Neural Patterns',
    type: 'ECoG',
    description:
      'Intracranial ECoG recordings from speech cortex during imagined and overt speech production. FDA-approved collection.',
    longDescription:
      "This dataset contains electrocorticography (ECoG) recordings from 6 patients with pharmacologically refractory epilepsy who had subdural electrode grids placed for clinical monitoring. During clinical monitoring, patients participated in speech production tasks. The grid covered the lateral surface of the left hemisphere including Broca's area, primary motor cortex, and superior temporal gyrus. Data sampled at 2000 Hz. Includes imagined speech (covert) and overt speech conditions for phonemes, words, and sentences.",
    dataPoints: 4_800_000,
    duration: '12 hours',
    samplingRate: '2000 Hz',
    channels: 128,
    price: '0.25',
    priceUSD: '$875',
    owner: '0x3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d',
    ownerName: 'Dr. Yuki Tanaka',
    requirements: {
      minEthBalance: '0.5',
      institutionRequired: true,
      purposeRequired: 'Speech-BCI Development',
      walletVerification: true,
    },
    tags: ["Speech", "Broca's Area", 'Intracranial', 'Language'],
    ipfsHash: 'QmZh5tY1oNmR0xVrP4bA9jD6eF8gC3lI7uM2wK1qO5oT',
    uploadedAt: '2025-12-10',
    verified: true,
    downloads: 8,
    status: 'restricted',
    maxPurchases: 3,
    purchaseCount: 0,
  },
  {
    id: 'bci-004',
    title: 'MEG Visual Processing Benchmark Set',
    type: 'MEG',
    description:
      'Whole-head MEG during passive viewing of 10,000 natural images. High SNR, preprocessed and trial-averaged versions included.',
    longDescription:
      'A large-scale MEG dataset for visual neuroscience and neural decoding research. Participants viewed 10,000 natural images from ImageNet across 2 sessions. The data was acquired using a 306-sensor ELEKTA Neuromag system at 1000 Hz. Both raw and preprocessed (SSS, temporal filtering 0.1–40 Hz, ICA artifact removal) versions are available. Trial-averaged ERFs and single-trial data are included. A companion deep learning feature set (ResNet-50) is provided for representational similarity analysis.',
    dataPoints: 30_600_000,
    duration: '20 hours',
    samplingRate: '1000 Hz',
    channels: 306,
    price: '0.08',
    priceUSD: '$280',
    owner: '0x4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e',
    ownerName: 'Dr. Amara Osei',
    requirements: {
      minEthBalance: '0.1',
      institutionRequired: false,
      purposeRequired: 'Visual Neuroscience',
      walletVerification: true,
    },
    tags: ['Visual Cortex', 'Object Recognition', 'Neural Decoding', 'ImageNet'],
    ipfsHash: 'QmAi6uZ2pOnS1yWsQ5cB0kE7fG9hD4mJ8vN3xL2rP6pU',
    uploadedAt: '2026-02-02',
    verified: true,
    downloads: 52,
    status: 'available',
    maxPurchases: undefined,
    purchaseCount: 0,
  },
  {
    id: 'bci-005',
    title: 'EMG Upper Limb Prosthetic Control',
    type: 'EMG',
    description:
      '16-channel surface EMG from forearm muscles during 52 hand gestures. Synchronized with kinematic ground truth via CyberGlove.',
    longDescription:
      'Surface EMG recordings from 20 able-bodied subjects and 5 transradial amputees performing 52 hand and wrist movements. 16 electrodes placed circumferentially around the forearm. Signals acquired at 2000 Hz using OT Bioelettronica Sessantaquattro. Kinematic ground truth provided by CyberGlove III for able-bodied subjects. Includes rest periods and movement transitions. Intended for prosthetic hand control, gesture recognition, and muscle synergy research.',
    dataPoints: 2_400_000,
    duration: '30 hours',
    samplingRate: '2000 Hz',
    channels: 16,
    price: '0.03',
    priceUSD: '$105',
    owner: '0x5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f',
    ownerName: 'Eng. Fatima Al-Rashid',
    requirements: {
      minEthBalance: '0.05',
      institutionRequired: false,
      purposeRequired: 'Prosthetics Research',
      walletVerification: false,
    },
    tags: ['Prosthetics', 'Hand Gestures', 'Muscle Synergy', 'Amputee'],
    ipfsHash: 'QmBj7vA3qPoT2zXtR6dC1lF8gH0iE5nK9wO4yM3sQ7qV',
    uploadedAt: '2026-02-18',
    verified: false,
    downloads: 71,
    status: 'available',
    maxPurchases: undefined,
    purchaseCount: 0,
  },
  {
    id: 'bci-006',
    title: 'fNIRS Cognitive Load Prefrontal Dataset',
    type: 'fNIRS',
    description:
      'Prefrontal fNIRS during n-back working memory tasks (0-back to 3-back). 52 channels, dual wavelength, 10 Hz sampling.',
    longDescription:
      'Functional near-infrared spectroscopy (fNIRS) dataset measuring hemodynamic responses in the prefrontal cortex during working memory tasks. 40 participants (20 young, 20 older adults) performed 0-back, 1-back, 2-back, and 3-back tasks. 52 channels covering the prefrontal and motor regions using a NIRx NIRSport2 system at 10 Hz, dual wavelength (760nm/850nm). Both oxy-Hb and deoxy-Hb signals are provided after Beer-Lambert conversion. Includes reaction time, accuracy, and NASA-TLX cognitive load scores.',
    dataPoints: 1_248_000,
    duration: '16 hours',
    samplingRate: '10 Hz',
    channels: 52,
    price: '0.02',
    priceUSD: '$70',
    owner: '0x6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a',
    ownerName: 'Dr. Lena Müller',
    requirements: {
      minEthBalance: '0.05',
      institutionRequired: false,
      purposeRequired: 'Cognitive Science',
      walletVerification: false,
    },
    tags: ['Working Memory', 'N-Back', 'Cognitive Load', 'Hemodynamics'],
    ipfsHash: 'QmCk8wB4rQpU3aYuS7eD2mG9hI1jF6oL0xP5zN4tR8rW',
    uploadedAt: '2026-03-01',
    verified: true,
    downloads: 28,
    status: 'available',
    maxPurchases: undefined,
    purchaseCount: 0,
  },
];
